### ISSUE TITLE
nmos-testing fails upon startup due to nameserver issues

### ISSUE THREAD

**Issue by dpotter-intoto** [rhastie/easy-nmos#15]
Thank you for authoring this orchestration layer.

I am wondering if you've seen this issue:   When started using docker-compose, the `nmos-testing` image fails upon startup because it is unable to resolve the hostname `github.com`.  

````
 File "nmos-test.py", line 19, in <module>
    NMOSTesting.main(sys.argv)
  File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 978, in main
    init_spec_cache()
  File "/home/nmos-testing/nmostesting/NMOSTesting.py", line 526, in init_spec_cache
    repo = git.Repo.clone_from('https://github.com/AMWA-TV/' + repo_data["repo"] + '.git', path)
  File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 1032, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 973, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.6/dist-packages/git/util.py", line 329, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/AMWA-TV/nmos-discovery-registration.git cache/is-04
  stderr: 'Cloning into 'cache/is-04'...
fatal: unable to access 'https://github.com/AMWA-TV/nmos-discovery-registration.git/': Could not resolve host: github.com
````
Interestingly, I don't have this problem if I manually start the container using `docker run -d -p "5000:5000" amwa/nmos-testing`.  I suspect it's related to docker-compose using a custom network.

Hoping you've encountered this and can offer some advice.

**Host OS:**  I've tested on Centos 7 and Ubuntu 20.04 with identical results
**docker** version 19.03.8, build afacb8b7f0
**docker-compose** version 1.27.4, build 40524192

System setup:

1.  Install fresh Ubuntu 20.04 (launch new AMI on AWS)
2.  `apt-get update`
3.  `apt-get install docker.io`
4.  (install docker-compose using curl/chmod)
5.  install easy-nmos using `git clone`
6.  Edit docker-compose.yml
  * three unique IP addresses in correct subnet
  * change parent interface name to match host interface name
  * change parent subnet range to match host subnet range
7.  `docker-compose pull`
8.  `docker-compose up`

**Comment by rhastie** [comment]
Ah... You appear to be running this in an AWS EC2 instance. You are effectively running this on top of a KVM hypervisor inside AWS. Your EC2 instance needs to support promiscuous mode on the NIC interface in order to support docker-compose using the "macvlan" driver.

easy-NMOS has not been tested inside an AWS EC2 instance and I'm not sure in terms of configuration you would need to make this function.

**Comment by dpotter-intoto** [comment]
Thanks for the fast response.

I've also repro'd the issue on a (physical, non-virtual) Centos 7 machine.  Possibly also an issue with promiscuous mode?

Will let you know if I make progress.

**Comment by rhastie** [comment]
Try running "ip link set eth1 promisc on" where "eth1" is the main server ethernet adapter you are pinning docker-compose to.

**Comment by dpotter-intoto** [comment]
Thanks again for the support.

Problems solved.  For posterity, on my Centos 7 physical machine, the following worked for me:

1.  Enable promiscuous mode on the adapter (I used `ifconfig enp3s2 promisc`, but of course use the proper adapter name on your box)
2.  I needed to add `gateway: 10.2.2.10` to **docker-compose.yml** underneath `driver_opts:`
3.  I also needed to remove the old network created by docker-compose to allow it to be recreated.  `docker network ls` shows the networks, then `docker network rm <netid>` removed the old **easy-nmos_external** network
4. At this point, `docker-compose up` resulted in a functioning stack for me.

Thanks again.

**Comment by garethsb** [comment]
Thanks for this! I reproduced this issue running easy-nmos inside an Ubuntu VM in VirtualBox on Windows. (The VirtualBox settings had the NIC set to promiscuous mode.)

@rhastie, I can confirm that both changes were necessary to get things to work for me.

1. `sudo ip link set enp0s3 promisc on` inside the VM
2. Add `gateway` line to `driver_opts` for the `external` network in **docker-compose.yml**
