### ISSUE TITLE
Off subnet availability

### ISSUE THREAD

**Issue by gadgieOps** [rhastie/easy-nmos#22]
Hi Richard,

First, thanks for providing this tool. I've been using it since it was first published and has been incredibly helpful for various different scenerios.

One use case I have continually had to configure is a gateway for the containers to talk to remote networks. I've found myself writing documentation for colleagues are various points over the years and figured I should probably raise an issue to cut out the middle man. 

The process is to create a macvlan outside of docker-compose using docker. This allows you to attach a gateway to the network. And then in the docker-compose.yml, reference the newly created network rather than create a new one. 

Would you be open to me submitting you a PR for a section in the README and an example docker-compose.yml file? More than happy to contribute.

Cheers!

**Comment by rhastie** [comment]
@gadgieOps More than happy to review a PR for the README.md. I suggest you submit it as a separate section to the README. This would be what I would describe as "advanced" Docker techniques and as such I'd prefer it if it didn't confuse the more simplified initial approach. We generally have to cater for people who are new to Docker in this repo.

More generally, I'm happy to support any contribution that supports the wider adoption and usage of both easy-NMOS and the underlying containers. Thanks, Rich!
