### ISSUE TITLE
Source and destination of created node is shown as example

### ISSUE THREAD

**Issue by stoton** [rhastie/easy-nmos#25]
Hello, I cannot find a configuration to change name of source and name of destination of device - when I add multiple instances of easy-nmos all are shown as example

**Comment by garethsb** [comment]
Do you mean the labels and descriptions on all resources?
Or the group hint tag on Senders and Receivers?

The former can easily be changed for each nmos-cpp-node instance with the `label` and `description` fields in _node.json_ config file.
Unfortunately, the latter cannot currently be changed declaratively, it's hard-coded in the example _nmos-cpp-node_ implementation.

Config file full spec - https://github.com/sony/nmos-cpp/blob/26ed65a93b56a4a1d0a82456a3fa3f36b745b0ca/Development/nmos-cpp-node/config.json

(Actually, rhastie/build-nmos-cpp that builds the nmos-cpp Docker image is currently a little way behind tip of sony/nmos-cpp master, so `node_tags` and `device_tags` mentioned there are not supported yet. We'll be updating the container image soon.)

Hard-coded group hint tag - https://github.com/sony/nmos-cpp/blob/26ed65a93b56a4a1d0a82456a3fa3f36b745b0ca/Development/nmos-cpp-node/node_implementation.cpp#L1405

**Comment by stoton** [comment]
Yes, thank you for your answer!
