### ISSUE TITLE
nmos-testing not starting?

### ISSUE THREAD

**Issue by BillClaghorn** [rhastie/easy-nmos#30]
Host Ubuntu 22.04.3 LTS
HOST IP 10.0.0.181

I don't see what's wrong with the settings/subnet/range.
The original docker-compose.yml with ipv4_address: '192.168.6.101' runs but IP doesn.t match host.

~/easy-nmos$ docker-compose up
[+] Running 0/0
 ⠋ Container nmos-registry  Creating                                       0.0s
Error response from daemon: invalid config for network easy-nmos_external: invalid endpoint settings:
no configured subnet or ip-range contain the IP address 10.0.0.191

~/easy-nmos$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:b8:8c:4a:59  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.181  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:640:c901:d9e0:463f:c6a7:a971:2ef4  prefixlen 64  scopeid 0x0<global>

docker-compose.yml :

version: '3.6'

services:

  # Create NMOS Registry/Controller container instance
  nmos-registry:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-registry
    hostname: nmos-registry
    domainname: local
    ports:
    - "80-81:80-81"
    - "1883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    networks: 
      external:
        ipv4_address: '10.0.0.191'

  # Create NMOS Virtual Node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode
    domainname: local
    ports:
    - "80-81:80-81"
    volumes:
    - "./node.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      external:
        ipv4_address: '10.0.0.192'
    depends_on:
    - nmos-registry    

  # Create AMWA NMOS Testing container instance
  nmos-testing:
    image: amwa/nmos-testing:latest
    container_name: nmos-testing
    hostname: nmos-testing
    domainname: local
    entrypoint: |
       /bin/bash -c "/etc/init.d/dbus start;
       /etc/init.d/avahi-daemon start;
       python3 nmos-test.py"
    ports:
    - "5000:5000"
    volumes:
    - "./UserConfig.py:/config/UserConfig.py"
    networks:
      external:
        ipv4_address: '10.0.0.193'
    depends_on:
    - nmos-virtnode

networks:
    external:
        # Create external macvlan subnet using host physical interface allowing containers to have their own IP addresses
        driver: macvlan
        driver_opts:
            parent: enp6s0
        ipam:
            config:
            - subnet: 10.0.0.0/24

**Comment by rhastie** [comment]
Bill,

Is this running in a VM or bare-metal? Ideally it needs to be bare-metal otherwise you'll introduce additional configuration challenges at the VM layer that aren't documented here. 

Looking at your output it doesn't appear that your 10.0.0.0 network is actually online properly. You should see LOWER_UP if everything is correct. LOWER_UP indicates that an Ethernet cable was plugged in and that the device is connected to the network. UP just means it's administratly enabled. 

I would start investigating here first. 

Thanks

**Comment by BillClaghorn** [comment]
Is this running in a VM or bare-metal?  bare-metal

I can ssh into the computer and access the internet. It's working. 

:~$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 58:11:22:46:8d:13 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.181/24 brd 10.0.0.255 scope global dynamic noprefixroute enp6s0
       valid_lft 170704sec preferred_lft 170704sec

**Comment by rhastie** [comment]
Ok. This is much better. Your NIC interface you are trying to bridge to is now showing online (LOWER_UP).

The next step I'm going to make a guess! Did you try the original docker-compose yaml first and then CRTL+C out of the docker-compose to make the changes? You may have left behind the original MACVLAN bridge which will still be configured in your system. This would inhibit you from creating another bridge on this interface even if you had changed the IP Address.

Please run "docker network ls". If you see an "easy-nmos_external" network shown you have a previous config in your system. If this is the case, please run either (or both) of the following:

"docker-compose down" - This is the best way to clean up as it'll reverse the full config OR
"docker network rm easy-nmos_external" - This will manually remove the MACVLAN bridge network from Docker

Finally, please re-run the "docker-compose up" command.

If there is no "easy-nmos_external" network please send me the output of the "docker network ls" command.

Thanks

**Comment by BillClaghorn** [comment]
That works. Thanks.

**Comment by rhastie** [comment]
Superb... Closing the issue
